version: "3.8"

services:

  mysql56:
    image: mysql:5.6
    container_name: "mysql56"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../mysql:/var/lib/mysql
      - ../publico:/publico
    ports:
      - 3306:3306

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../sistemas:/var/www
      - ../publico:/publico
    ports:
      - 80:80
      - 8000:8000

  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql56